{'filename': 'C:\\Users\\Pain panda\\Downloads\\codigo_fonte_projeto\\untitled\\app\\processamento\\previsao_series\\previsao.py', 'lineno': 145, 'name': 'save', 'type': 'AttributeError', 'message': AttributeError("'rede_neural' object has no attribute 'save_fited_model'",)}
{'filename': 'C:\\Users\\Pain panda\\Downloads\\codigo_fonte_projeto\\untitled\\app\\processamento\\previsao_series\\previsao.py', 'lineno': 208, 'name': 'load_previsao', 'type': 'KeyError', 'message': KeyError('geometria_modelo',)}
{'filename': 'C:\\Users\\Pain panda\\Downloads\\codigo_fonte_projeto\\untitled\\app\\libs\\MLP\\mlp_lib.py', 'lineno': 87, 'name': 'fit', 'type': 'ValueError', 'message': ValueError('Expected 2D array, got 1D array instead:\narray=[].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.',)}
{'filename': 'C:\\Users\\Pain panda\\Downloads\\codigo_fonte_projeto\\untitled\\app\\processamento\\previsao_series\\previsao.py', 'lineno': 110, 'name': 'prever_serie', 'type': 'TypeError', 'message': TypeError("unsupported operand type(s) for *: 'int' and 'NoneType'",)}
{'filename': 'C:\\Users\\Pain panda\\Downloads\\codigo_fonte_projeto\\untitled\\app\\libs\\MLP\\mlp_lib.py', 'lineno': 38, 'name': 'criar_modelo', 'type': 'TypeError', 'message': TypeError("__init__() got an unexpected keyword argument 'max_iterations'",)}
{'filename': 'C:\\Users\\Pain panda\\Downloads\\codigo_fonte_projeto\\untitled\\app\\libs\\MLP\\mlp_lib.py', 'lineno': 84, 'name': 'fit', 'type': 'AttributeError', 'message': AttributeError("'NoneType' object has no attribute 'fit'",)}
